The following modules were not unloaded:
  (Use "module --force purge" to unload all):

  1) nvidia/.latest   2) slurm/.latest
/fred/oz413/.conda/envs/llm-env/lib/python3.10/site-packages/transformers/utils/generic.py:311: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
/fred/oz413/.conda/envs/llm-env/lib/python3.10/site-packages/transformers/utils/generic.py:311: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
/fred/oz413/.conda/envs/llm-env/lib/python3.10/site-packages/peft/utils/save_and_load.py:198: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  adapters_weights = torch.load(filename, map_location=torch.device(device))
05/23/2025 16:36:47 - INFO - __main__ - Successfully load models
05/23/2025 16:36:47 - INFO - __main__ - Pad token id is None, setting to eos token id...
Traceback (most recent call last):
  File "/fred/oz413/ANeurIPS2024_SPV-MIA/attack.py", line 98, in <module>
    train_dataset, valid_dataset = dataset_prepare(cfg, tokenizer=tokenizer)
  File "/fred/oz413/ANeurIPS2024_SPV-MIA/data/prepare.py", line 119, in dataset_prepare
    raw_dataset = load_from_disk(dataset_path)
  File "/fred/oz413/.conda/envs/llm-env/lib/python3.10/site-packages/datasets/load.py", line 2252, in load_from_disk
    raise FileNotFoundError(
FileNotFoundError: Directory /fred/oz413/LLM/ag_news is neither a `Dataset` directory nor a `DatasetDict` directory.
